# Generated by Django 2.2 on 2019-08-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('message', models.TextField(verbose_name='message')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'message',
                'db_table': 'my_message',
            },
        ),
    ]
