# Generated by Django 2.2 on 2019-08-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_form', '0002_auto_20190825_1744'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
